"""Where things live. One definition, imported by every job."""
from __future__ import annotations

from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BACKEND_DIR.parent

DATA_DIR = REPO_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
CLEAN_DIR = DATA_DIR / "clean"
RAW_MEASUREMENTS = RAW_DIR / "measurements"
STATIONS_PARQUET = RAW_DIR / "stations.parquet"
SENSORS_PARQUET = RAW_DIR / "sensors.parquet"
PROVENANCE_JSON = RAW_DIR / "provenance.json"

DOCS_DIR = REPO_DIR / "docs"
LOGS_DIR = REPO_DIR / "logs"
POWERBI_DIR = REPO_DIR / "powerbi"
ANALYSIS_DIR = REPO_DIR / "analysis"
FRONTEND_PUBLIC = REPO_DIR / "frontend" / "public"

# The banner that must appear on every artefact derived from generated
# measurements. Written once here so it cannot drift between files.
SYNTHETIC_BANNER = (
    "SYNTHETIC MEASUREMENTS. Station names, cities and coordinates are real "
    "CPCB/OpenAQ monitoring sites; every concentration value in this dataset "
    "was generated by backend/jobs/synth.py. Do not cite these numbers. "
    "Set OPENAQ_API_KEY in backend/.env and re-run collect.py for real data."
)


def ensure_dirs() -> None:
    for path in (RAW_DIR, CLEAN_DIR, RAW_MEASUREMENTS, DOCS_DIR, LOGS_DIR,
                 POWERBI_DIR, FRONTEND_PUBLIC):
        path.mkdir(parents=True, exist_ok=True)
